In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset=load_iris()

In [4]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [10]:
dataset['target'] = dataset.target

In [11]:
dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
df =pd.DataFrame(dataset.data , columns=dataset.feature_names)

In [13]:
df.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
116                6.5               3.0                5.5               1.8
136                6.3               3.4                5.6               2.4
125                7.2               3.2                6.0               1.8
141                6.9               3.1                5.1               2.3
140                6.7               3.1                5.6               2.4

In [14]:
df['target']=dataset.target

In [17]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [21]:
df_copy = df[df['target']!=2]

In [23]:
df_copy.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
65                6.7               3.1                4.4               1.4   
0                 5.1               3.5                1.4               0.2   
66                5.6               3.0                4.5               1.5   
99                5.7               2.8                4.1               1.3   
84                5.4               3.0                4.5               1.5   

    target  
65       1  
0        0  
66       1  
99       1  
84       1

# independent and dependent features 

In [24]:
X = df_copy.iloc[:,:-1]
Y = df_copy.iloc[:,-1]

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test ,Y_train,Y_test = train_test_split(X,Y , test_size=0.20, random_state=42)


In [28]:
from sklearn.linear_model import LogisticRegression 
clf = LogisticRegression()

In [29]:
clf.fit(X_train,Y_train)

LogisticRegression()

In [36]:
clf.predict_proba(X_test)

array([[0.00118085, 0.99881915],
       [0.01580857, 0.98419143],
       [0.00303433, 0.99696567],
       [0.96964813, 0.03035187],
       [0.94251523, 0.05748477],
       [0.97160984, 0.02839016],
       [0.99355615, 0.00644385],
       [0.03169836, 0.96830164],
       [0.97459743, 0.02540257],
       [0.97892756, 0.02107244],
       [0.95512297, 0.04487703],
       [0.9607199 , 0.0392801 ],
       [0.00429472, 0.99570528],
       [0.9858324 , 0.0141676 ],
       [0.00924893, 0.99075107],
       [0.98144334, 0.01855666],
       [0.00208036, 0.99791964],
       [0.00125422, 0.99874578],
       [0.97463766, 0.02536234],
       [0.96123726, 0.03876274]])

In [39]:
## prediction 
y_pred = clf.predict(X_test)

In [40]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

# Confusion matrix,accuracy score,classification report

In [41]:
from sklearn.metrics import confusion_matrix , accuracy_score ,classification_report 

In [42]:
confusion_m =confusion_matrix(y_pred , Y_test)
acc_score = accuracy_score(y_pred, Y_test)
clf_report =classification_report(y_pred,Y_test)

In [43]:
print("confusion_m" ,confusion_m)
print("acc_score",acc_score)
print("clf_report",clf_report)

confusion_m [[12  0]
 [ 0  8]]
acc_score 1.0
clf_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [44]:
# hyperparameter tunning


In [46]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [47]:
parameter= { 'penalty' : ('l1','l2','elasticnet' , None) ,'C':[1,10,20]}


In [49]:
gscv =GridSearchCV(clf,param_grid=parameter , cv=5)


In [50]:
gscv.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [51]:
gscv.best_params_

{'C': 1, 'penalty': 'l2'}

In [53]:
clf = LogisticRegression(C=1,penalty='l2')


In [54]:
clf.fit(X_train,Y_train)

LogisticRegression(C=1)

In [59]:
y_pred=clf.predict(X_test)
confusion_m =confusion_matrix(y_pred , Y_test)
acc_score = accuracy_score(y_pred, Y_test)
clf_report =classification_report(y_pred,Y_test)

In [60]:
print("confusion_m" ,confusion_m)
print("acc_score",acc_score)
print("clf_report",clf_report)

confusion_m [[12  0]
 [ 0  8]]
acc_score 1.0
clf_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [61]:
from sklearn.model_selection import RandomizedSearchCV

In [63]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameter,cv=5)

In [64]:
random_clf.fit(X_train , Y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [65]:
random_clf.best_params_

{'penalty': None, 'C': 10}

In [68]:
rclf = LogisticRegression(C=10,penalty=None)


In [69]:
rclf.fit(X_train,Y_train)

LogisticRegression(C=10, penalty=None)

In [72]:
y_predr=rclf.predict(X_test)
confusion_m =confusion_matrix(y_predr , Y_test)
acc_score = accuracy_score(y_predr, Y_test)
clf_report =classification_report(y_predr,Y_test)

In [73]:
print("confusion_m" ,confusion_m)
print("acc_score",acc_score)
print("clf_report",clf_report)

confusion_m [[12  0]
 [ 0  8]]
acc_score 1.0
clf_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

